### ISSUE TITLE
Font only loads over HTTPS

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/charsheet#38]
This is strange behaviour we're seeing on OpenShift. The line which loads the font doesn't specify a URI, so we need to investigate this issue. Check it, in `app.css`:

``` css
@font-face {
    font-family: "Jura Light";
    font-style: normal;
    font-weight: 400;
    src: local('Jura Light'), local('JuraLight'), url("../fonts/JuraLight.woff")
            format('woff');
}
```
